[build]
  command = "yarn build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "TUO_SUPABASE_ANON_KEY"
  NEXT_PUBLIC_SUPABASE_URL = "TUO_SUPABASE_URL"
  NEXT_PUBLIC_TMDB_API_KEY = "TUO_TMDB_API_KEY"

[[plugins]]
  package = "@netlify/plugin-nextjs"
