[build]
  command = "yarn build"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "..."
  NEXT_PUBLIC_SUPABASE_URL = "..."
  NEXT_PUBLIC_TMDB_API_KEY = "..."

[[plugins]]
  package = "@netlify/plugin-nextjs"
