[build]
  command = "yarn build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"  # Assicurati che corrisponda alla tua versione locale
  NEXT_TELEMETRY_DISABLED = "1"

  # Variabili per Supabase
  DATABASE_URL = "postgresql://postgres:VinciWolf27.WV@db.ejhzktruqgflyysoxmxd.supabase.co:5432/postgres?schema=public"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtweGptdWl5cHp4eGlwZXlkdGNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNTQ3MDgsImV4cCI6MjA3MDkzMDcwOH0.eIZe41uevL0tsiIdBBW3WFeX5gv9KwbbdGfLNmgebSI"
  NEXT_PUBLIC_SUPABASE_URL = "https://kpxjmuiypzxxipeydtcf.supabase.co"

  # Variabili TMDB
  NEXT_PUBLIC_TMDB_API_KEY = "ed4153f187bc4e376c643e5eb93cc810"

[[plugins]]
  package = "@netlify/plugin-nextjs"
