[build]
  command = "npm run build"
  publish = ".out"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
  NEXT_PUBLIC_SUPABASE_URL = "https://kpxjmuiypzxxipeydtcf.supabase.co"
  NEXT_PUBLIC_TMDB_API_KEY = "ed4153f187bc4e376c643e5eb93cc810"

[[plugins]]
  package = "@netlify/plugin-nextjs"
